.github/workflows/push-to-main.yml
F2F-76t1 (test 1) Corrected an old directory reference.
=> F2F-76: Merge to main workflow testing

.secrets.baseline, deploy.sh
Added new backend stack ref in deploy.sh
So frontend and backend stack-name are align
- [F2F-152](https://govukverify.atlassian.net/browse/F2F-152)
[F2F-152]: https://govukverify.atlassian.net/browse/F2F-152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-152 -Backend stack name ref updated

.github/dependabot.yml, .github/workflows/post-merge-deploy-to-dev.yml, .github/workflows/pre-merge-integration-test.yml
Modified most merge workflow similar to pre-merge integration checks
So PR gets merge to diff environment
- [F2F-225](https://govukverify.atlassian.net/browse/F2F-225)
=> F2F-225 Modified GH action in post merge workflow

.github/workflows/post-merge-deploy-to-dev.yml, .github/workflows/post-merge-package-to-build.yml
Code signing step are now covered by SAM Deploy steps provided by Dev Platform
For code to deployin build
- [F2F-225](https://govukverify.atlassian.net/browse/F2F-225)
[F2F-225]: https://govukverify.atlassian.net/browse/F2F-225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-225 Single steps to cover code signing and deploy

infrastructure/template.yaml
Lambda permission boundary.
Build deployment was failing due to lambda permission issue
- [F2F-225](https://govukverify.atlassian.net/browse/F2F-225)
[F2F-225]: https://govukverify.atlassian.net/browse/F2F-225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[F2F-225]: https://govukverify.atlassian.net/browse/F2F-225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-225 Troubleshoot lambda permision issue with dev-platform help

infrastructure/template.yaml
Setting concurrency to 0 in build env.
throwing error in build env.
- [F2F-225](https://govukverify.atlassian.net/browse/F2F-225)
[F2F-225]: https://govukverify.atlassian.net/browse/F2F-225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-225c Set provisionedConcurrency to 0

.github/workflows/push-to-main.yml
Small fix to deploy-to-build step
=> Small fix to deploy-to-build pipeline

.github/workflows/pull-request-KMS.yml, infra-l2-kms/.gitignore, infra-l2-kms/jest.config.ts, infra-l2-kms/package-lock.json, infra-l2-kms/package.json, infra-l2-kms/src/tests/infra/infra.test.ts, infra-l2-kms/template.yaml, infra-l2-kms/tsconfig.json
Add KMS keys and aliases for JAR encryption and a Test signing key
Asymmetric KMS keys must be in independent stacks for stability
- [F2F-294](https://govukverify.atlassian.net/browse/F2F-294)
[F2F-294]: https://govukverify.atlassian.net/browse/F2F-294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-294] Create L2 stack for KMS keys

deploy/template.yaml
Adding L2 stack name
For BE pipeline to pickup L2 value
- [F2F-318](https://govukverify.atlassian.net/browse/F2F-318)
[F2F-318]: https://govukverify.atlassian.net/browse/F2F-318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-318 Adding L2 stack name as default

infra-l2-dynamo/template.yaml
Adding the authorizationCode index.
- [F2F-306](https://govukverify.atlassian.net/browse/F2F-306)
- [F2F-307](https://govukverify.atlassian.net/browse/F2F-307)
[F2F-306]: https://govukverify.atlassian.net/browse/F2F-306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[F2F-307]: https://govukverify.atlassian.net/browse/F2F-307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-306] dynamo db updates- Adding the authorizationCode index

deploy/template.yaml
Moving CIC Lambdas to Protected Subnet
=> Moving CIC Lambdas to Protected Subnet

deploy/template.yaml, src/services/AuthorizationRequestProcessor.ts, src/services/UserInfoRequestProcessor.ts, src/tests/unit/services/UserInfoRequestProcessor.test.ts, src/utils/TxmaEvent.ts, src/utils/VerifiableCredentialService.ts
Added the code to send TXMA event once the signed VC is successfully generated.
Evidences attached to the ticket for reference.
Unit-tests added for success and failure use-cases.
- [F2F-109](https://govukverify.atlassian.net/browse/F2F-109)
- Added TXMA_QUEUE_URL which references to the TXMA sqs queue where the TXMA events needs to be sent.
[F2F-109]: https://govukverify.atlassian.net/browse/F2F-109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-109]-TXMA event code changes for userInfo endpoint

deploy/template.yaml
Reverts alphagov/di-ipv-cri-cic-api#86
=> Revert "Moving CIC Lambdas to Protected Subnet"

.github/CODEOWNERS
Added CODEOWNERS file in order to control who can review PRs
- [F2F-366](https://govukverify.atlassian.net/browse/F2F-366)
[F2F-366]: https://govukverify.atlassian.net/browse/F2F-366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-366: Add CODEOWNERS file

.github/workflows/post-merge-waf-build.yml, .github/workflows/post-merge-waf-dev.yml, .github/workflows/pull-request-WAF.yml, .gitignore, infra-l2-waf/README.md, infra-l2-waf/jest.config.ts, infra-l2-waf/package-lock.json, infra-l2-waf/package.json, infra-l2-waf/template.yaml, infra-l2-waf/tests/waf.test.ts
Add WAF github actions workflows for DEV and BUILD
Add WAF template & tests
- [F2F-316](https://govukverify.atlassian.net/browse/F2F-316)
- [PLAT-854](https://govukverify.atlassian.net/browse/PLAT-854)
[PLAT-854]: https://govukverify.atlassian.net/browse/PLAT-854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[F2F-316]: https://govukverify.atlassian.net/browse/F2F-316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PLAT-854: Add WAF workflows and template

.github/workflows/post-merge-package-to-build.yml, .github/workflows/post-merge-package-to-dev.yml
Don't trigger api workflows on waf changes.
=> api workflow to ignore WAF changes

.github/workflows/post-merge-ipv-stub-package-to-build.yml, .github/workflows/post-merge-ipv-stub-package-to-dev.yml, cic-ipv-stub/README.md
Remove signing stage from GH workflow
=> Remove signing stage from GH workflow

cic-ipv-stub/template.yaml
=> Rename IPV stub API Export

.github/workflows/pull-request-Dynamo.yml, deploy/template.yaml
Added cron job in JsonWebKeysFunction
For Lambda function to run every hour
- [F2F-411](https://govukverify.atlassian.net/browse/F2F-411)
[F2F-411]: https://govukverify.atlassian.net/browse/F2F-411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-411 Adding cron job for lambda to run every hour

infra-l2-waf/template.yaml
Ensure the WAF log-group is created before it's used.
=> Fix waf template dependency

src/tests/unit/data/verified_credential.ts, src/tests/unit/services/VerifiableCredentialService.test.ts, src/tests/unit/utils/MockJwtVerifierSigner.ts, src/utils/Constants.ts, src/utils/IVeriCredential.ts, src/utils/VerifiableCredentialService.ts
VC Restructuring
VC was updated per IPV. Added jti claim, removed exp claim and other unwanted claims from the jwt.
Also restructured the user name per the VC format provided in the RFC, separating the givenName and familyName and adding it as separate values as stored in the DB table.
- [F2F-409](https://govukverify.atlassian.net/browse/F2F-409)
Evidence for the Acs attached to the ticket for reference.
[F2F-409]: https://govukverify.atlassian.net/browse/F2F-409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-409] Update VC structure generated by /userInfo

.github/workflows/pull-request-KMS.yml, .github/workflows/pull-request-WAF.yml, .github/workflows/pull-request-ipv-stub.yml, .github/workflows/pull-request.yml, .secrets.baseline
Modifying how detect secret will scan all file
=> Modifying detect secret to scan all file

deploy/template.yaml
Added CSLS to send logs
- [F2F-484](https://govukverify.atlassian.net/browse/F2F-484)
[F2F-484]: https://govukverify.atlassian.net/browse/F2F-484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-484 CSLS Integration to send logs

.gitignore, deploy/cic-spec.yaml, deploy/samconfig.toml, src/.gitignore, src/README.md, src/events/claimedid-event.json, src/models/CicSession.ts, src/models/ISessionItem.ts, src/package-lock.json, src/services/CicService.ts, src/tests/unit/data/auth-events.ts, src/tests/unit/data/cic-events.ts, src/tests/unit/models/CicSession.test.ts, src/tests/unit/services/AccessTokenRequestProcessor.test.ts, src/tests/unit/services/AuthorizationRequestProcessor.test.ts, src/tests/unit/services/CicService.test.ts, src/tests/unit/services/ClaimedIdRequestProcessor.test.ts, src/tests/unit/services/UserInfoRequestProcessor.test.ts, src/tests/unit/services/VerifiableCredentialService.test.ts, src/utils/ValidationHelper.ts
https://govukverify.atlassian.net/browse/F2F-277
Removed all references to _document_selected_ and _document_expiry_date_ from F2F BE code. Tested /claimedIdentity endpoint via updated F2F FE, using only first/family/given names and DOB. Screenshots attached. 
FE:
Successful endpoint call with updated request body:
Values successfully saved against session item:
Notes:
https://govukverify.atlassian.net/browse/F2F-276 - Current OpenAPI version is up to date.
https://govukverify.atlassian.net/browse/F2F-423 - FE payload as demonstrated in screenshot
=> F2F-277/276/423

.github/workflows/pull-request.yml, .github/workflows/sonar-analysis-on-merge.yml, sonar-project.properties
Added Sonar workflow file and add coverage
- [F2F-100](https://govukverify.atlassian.net/browse/F2F-100)
[F2F-100]: https://govukverify.atlassian.net/browse/F2F-100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F- 100 Adding separate file for sonar scan and add coverage

.github/workflows/pull-request-sonar.yml
Fix for Sonar Scan Code coverage 0% on Backend repos.
Removed the test infra before run the sonar scan
- [F2F-603](https://govukverify.atlassian.net/browse/F2F-603)
[F2F-603]: https://govukverify.atlassian.net/browse/F2F-603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-603: Fix for Sonar code coverage issue

.github/workflows/pull-request.yml, cic-ipv-stub/template.yaml, deploy/template.yaml, src/tests/infra/template.test.ts
Taking all ApiGateway Mapping resources out of the cic-infra repo and moving them the the api repo to remove circular dependency 
- [F2F-593](https://govukverify.atlassian.net/browse/F2F-593?search_id=56ab5c06-6c4b-481e-8d17-541ddcfcf728)
[F2F-593]: https://govukverify.atlassian.net/browse/F2F-593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-593: Mapping of BE APIGW to Custom Domain

deploy/template.yaml
Add specific MethodSettings to the BE REST APIGW for all methods
Ensure logging, tracing and default rate limits are in place
- [F2F-607](https://govukverify.atlassian.net/browse/F2F-607)
[F2F-607]: https://govukverify.atlassian.net/browse/F2F-607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-607 Add MethodSettings to BE REST APIGW

deploy/template.yaml
[JIRA Ticket](https://govukverify.atlassian.net/browse/F2F-748)
=> [F2F-748]: Modifying redirect urls as per integ testing

deploy/cic-spec.yaml
[JIRA ticket ](https://govukverify.atlassian.net/browse/F2F-759)
=> [F2F-759]: Modify success response code for /token

deploy/cic-spec.yaml, deploy/template.yaml, src/models/enums/ResourcesEnum.ts, src/tests/api/e2eHappyPath.test.ts, src/tests/unit/data/userInfo-events.ts, src/tests/utils/ApiTestSteps.ts
[JIRA Ticket](https://govukverify.atlassian.net/browse/F2F-759)
=> [F2F-759]: Modifying userInfo path

Dockerfile
Added awscli to docker image for test container. 
aws cli is required by the test codepipeline script.
- [F2F-764](https://govukverify.atlassian.net/browse/F2F-764)
[F2F-764]: https://govukverify.atlassian.net/browse/F2F-764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Added awscli to docker image to allow code pipeline test execution

run-tests.sh
- [F2F-768](https://govukverify.atlassian.net/browse/F2F-768)
[F2F-768]: https://govukverify.atlassian.net/browse/F2F-768?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Updated run-test.sh to copy tests reports to correct directory

.github/pull_request_template.md
Add check in PR template for PII data in log
To remind us when raising a PR
=> [CIC]: Add check in PR template

.github/workflows/post-merge-dynamo-to-build.yml, .github/workflows/post-merge-dynamo-to-dev.yml, .github/workflows/post-merge-ipv-stub-package-to-build.yml, .github/workflows/post-merge-ipv-stub-package-to-dev.yml, .github/workflows/post-merge-kms-build.yml, .github/workflows/post-merge-kms-dev.yml, .github/workflows/post-merge-package-to-build.yml, .github/workflows/post-merge-package-to-dev.yml, .github/workflows/post-merge-waf-build.yml, .github/workflows/post-merge-waf-dev.yml, .github/workflows/pull-request-Dynamo.yml, .github/workflows/pull-request-KMS.yml, .github/workflows/pull-request-WAF.yml, .github/workflows/pull-request-ipv-stub.yml, .github/workflows/pull-request.yml
GHA pipeline step aws-actions/setup-sam@v2 failing as below:
Adding change as suggested [here](https://gds.slack.com/archives/C02R5AB0VV0/p1689611069795149)
- [F2F-949](https://govukverify.atlassian.net/browse/F2F-949)
[F2F-949]: https://govukverify.atlassian.net/browse/F2F-949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-949]: To resolve aws-actions/setup-sam@v2 breaking

cic-ipv-stub/samconfig.toml, cic-ipv-stub/src/handlers/startCicCheck.ts, cic-ipv-stub/src/tests/startCicCheck.test.ts, cic-ipv-stub/template.yaml
- [F2F-XXX](https://govukverify.atlassian.net/browse/F2F-XXX)
=> [CIC-962] Fix IPV stub response

infra-l2-dynamo/template.yaml
Reverting clientSessionId from existing index as GSI updates are not allowed.
Fix the DDB pipeline error.
- [F2F-1080](https://govukverify.atlassian.net/browse/F2F-1080)
[F2F-1080]: https://govukverify.atlassian.net/browse/F2F-1080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-1080]Reverting clientSessionId from existing index 

test-harness/template.yaml
Change to description of test harness
Forcing Api Gateway stage to redeploy
=> Forcing test harness Api Gateway stage to redeploy

src/package-lock.json
npm ci used to install the node packages in the test container fail due to differences in package.json and package-lock.json. Reran npm install to so we do not see errors while running npm ci.
Post merge workflow to commit test container image failed to build the container image. 
- [F2F-1120](https://govukverify.atlassian.net/browse/F2F-1120)
[F2F-1120]: https://govukverify.atlassian.net/browse/F2F-1120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Updating package-lock.json for container tests

infra-l2-dynamo/template.yaml
Matches CIC Dynamo Main template to match what's in prod
Fix Prod Deployment for CIC
=> [KIWI-1211] Reset Dynamo index to match Prod

infra-l2-dynamo/template.yaml
Reverts alphagov/di-ipv-cri-cic-api#310
=> Revert "[KIWI-1211] Reset Dynamo index to match Prod"

run-tests.sh, src/tests/api/e2eHappyPath.test.ts, src/tests/utils/ApiTestSteps.ts, test-harness/test-harness-spec.yaml
Re-adds apigw security policy
To secure our endpoints
- [F2F-1268](https://govukverify.atlassian.net/browse/F2F-1268)
=> KIWI-1268 re-implements sigv4 in CIC

src/tests/utils/ApiTestSteps.ts
Amended the ApiTestSteps test file
Updated the call to the endpoints 
The path variable stored the endpoint but this was not being used and the call to the endpoint was hard coded 
The code was updated to uphold coding standards and uniformity
=> CIC-API-PATH-AMEND update ApiTestSteps file.

deploy/template.yaml
Created log metrics and alarms to:
Add log metric filter and alarm for S3 bucket policy changes
Add log metric filter and alarm for changes to network gateways
Add log metric filter and alarm for route table changes
Add log metric filter and alarm when changes are made to VPC
Add log metric and alarm when changes are made to AWS Organisations
Correct monitoring misconfigurations on CIC
- [KIWI-1225](https://govukverify.atlassian.net/browse/F2F-XXX)
[KIWI-1225]: https://govukverify.atlassian.net/browse/KIWI-1225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-1225] - Correct Monitoring Misconfigurations on CIC

deploy/template.yaml
Revert "Revert "KIWI-1502:Enable Lambda metrics in Dynatrace (#380) (#382)"
This reverts commit 06e62fb8fbc82b4f5809beb5099a690c7fe1e4ad.
Revert "Revert "KIWI-1502:Enable Lambda metrics in Dynatrace (#380) (#382)"
This reverts commit 06e62fb8fbc82b4f5809beb5099a690c7fe1e4ad.
- [KIWI-1502](https://govukverify.atlassian.net/browse/KIWI-1502)
[KIWI-1502]: https://govukverify.atlassian.net/browse/KIWI-1502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Revert "Revert "KIWI-1502:Enable Lambda metrics in Dynatrace (#380) (#382)"

src/tests/api/HappyPath.test.ts, src/tests/api/e2eHappyPath.test.ts, src/tests/api/e2eNegativePath.test.ts, src/tests/data/happyPathBillyJoe.json, src/tests/data/happyPathBjörn.json, src/tests/data/happyPathManuel.json, src/tests/data/happyPathSlim.json, src/tests/utils/ApiConstants.ts, src/tests/utils/ApiTestSteps.ts
Added automated tests for both F2F and No PID journeys within the /session endpoint.
- [KIWI-1470](https://govukverify.atlassian.net/browse/KIWI-1470)
- [KIWI-1472](https://govukverify.atlassian.net/browse/KIWI-1472)
[KIWI-1470]: https://govukverify.atlassian.net/browse/KIWI-1470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KIWI-1472]: https://govukverify.atlassian.net/browse/KIWI-1472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-1470] QA

.github/workflows/post-merge-dynamo-to-build.yml, .github/workflows/post-merge-dynamo-to-dev.yml, .github/workflows/post-merge-ipv-stub-package-to-build.yml, .github/workflows/post-merge-ipv-stub-package-to-dev.yml, .github/workflows/post-merge-kms-build.yml, .github/workflows/post-merge-kms-dev.yml, .github/workflows/post-merge-package-to-build.yml, .github/workflows/post-merge-package-to-dev.yml, .github/workflows/post-merge-push-test-container-to-build.yml, .github/workflows/post-merge-push-test-container-to-dev.yml, .github/workflows/pre-commit.yml, .pre-commit-config.yaml, .secrets.baseline, README.md
- Added pre-commit workflow
- Updated pre-commit hooks
- Updated readme
- Align with other repos across identity pod
- General housekeeping
- [IPS-484](https://govukverify.atlassian.net/browse/IPS-484)
[IPS-484]: https://govukverify.atlassian.net/browse/IPS-484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-486: Add pre-commit

src/tests/api/HappyPath.test.ts, src/tests/api/e2eHappyPath.test.ts, src/tests/utils/ApiTestSteps.ts
Add check for context field in CIC_CRI_START TxMA Event 
New requirement added as part of KIWI-1665
- [KIWI-1665](https://govukverify.atlassian.net/browse/KIWI-1665)
[KIWI-1665]: https://govukverify.atlassian.net/browse/KIWI-1665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Kiwi 1665 qa

src/tests/api/e2eHappyPath.test.ts, src/tests/data/CIC_CRI_AUTH_CODE_ISSUED_SCHEMA.json, src/tests/data/CIC_CRI_END_SCHEMA.json, src/tests/data/CIC_CRI_START_SCHEMA.json, src/tests/data/CIC_CRI_VC_ISSUED_SCHEMA.json
Update JSON Schema for TxMA checks to include event_timestamp_ms
- [KIWI-1585](https://govukverify.atlassian.net/browse/KIWI-1585)
[KIWI-1585]: https://govukverify.atlassian.net/browse/KIWI-1585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TxMA JSON Schema Updates

cic-ipv-stub/src/handlers/startCicCheck.ts
Pass custom frontend URL to IPV Stub
=> [KIWI-1559] - Enable use of custom frontend urls

src/services/SessionRequestProcessor.ts
Move govuk-signin-journey-id to Logger Context earlier as soon the jwt is decoded.
prod errors not capturing the journey-id earlier hence issues with missing info in shared_claims are being missed
- [KIWI-1692](https://govukverify.atlassian.net/browse/KIWI-1692)
[KIWI-1692]: https://govukverify.atlassian.net/browse/KIWI-1692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-1692]Move govuk-signin-journey-id to Logger Context earlier 

run-tests-locally.sh, run-tests.sh
Update run-tests logic to output report for failed test runs
Store report for failed runs in CodeBuild
- [KIWI-1685](https://govukverify.atlassian.net/browse/KIWI-1685)
[KIWI-1685]: https://govukverify.atlassian.net/browse/KIWI-1685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1685 QA CIC

deploy/template.yaml
- Add the missing IsNotDevelopment condition
- IsNotDevelopment environment condition missing on the previous commit. 
- [KIWI-1717](https://govukverify.atlassian.net/browse/KIWI-1717)
[KIWI-1717]: https://govukverify.atlassian.net/browse/KIWI-1717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1717: Add missing isNotDevelopment condition

.github/workflows/pull-request.yml, src/.env.contract, src/README.md, src/package-lock.json, src/package.json, src/tests/contract/CicCriProvider.test.ts, src/tests/contract/routes/AccessTokenRoute.ts, src/tests/contract/routes/UserInfoRoute.ts, src/tests/contract/scripts/test-pact-connection.sh, src/utils/KmsJwtAdapter.ts
Add contract tests as part of pre-merge checks and run the git-hub actions to execute these tests.
Added git-hub secrets related to pact-broker url, credentials.
Updated README file to run contract tests.
Contract testing MVP
- [KIWI-1788](https://govukverify.atlassian.net/browse/KIWI-1788)
[KIWI-1788]: https://govukverify.atlassian.net/browse/KIWI-1788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-1788] Integrate with PactBroker

src/jest.config.ts, src/package-lock.json, src/package.json
Added test report generation for Jest.
- [KIWI-1898](https://govukverify.atlassian.net/browse/KIWI-1898)
[KIWI-1898]: https://govukverify.atlassian.net/browse/KIWI-1898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update Jest.config with html reporter CIC

.github/workflows/post-merge-dynamo-to-build.yml, .github/workflows/post-merge-dynamo-to-dev.yml, .github/workflows/post-merge-ipv-stub-package-to-build.yml, .github/workflows/post-merge-ipv-stub-package-to-dev.yml, .github/workflows/post-merge-kms-build.yml, .github/workflows/post-merge-kms-dev.yml, .github/workflows/post-merge-package-to-build.yml, .github/workflows/post-merge-package-to-dev.yml, .github/workflows/post-merge-test-harness-package-to-build.yml, .github/workflows/post-merge-test-harness-package-to-dev.yml
- Update upload action version v3 to v3.8.1
- Update the sam build template path
- Update upload action version v3 to v3.8.1 and add the full sam build path
- [IPS-815](https://govukverify.atlassian.net/browse/IPS-815)
[IPS-815]: https://govukverify.atlassian.net/browse/IPS-815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-815: Update Upload action version

cic-ipv-stub/package-lock.json, cic-ipv-stub/package.json, cic-ipv-stub/src/tests/infrastructure.test.ts, infra-l2-dynamo/package-lock.json, infra-l2-dynamo/package.json, infra-l2-dynamo/src/tests/infra/infra.test.ts, infra-l2-kms/package-lock.json, infra-l2-kms/package.json, infra-l2-kms/src/tests/infra/infra.test.ts, src/package-lock.json, src/package.json, src/tests/infra/template.test.ts
Migrate from AWS CDK v1 to AWS CDK v2
To address vulnerabilities
=> CIC | BE | Migrate from AWS CDK v1 to AWS CDK v2

src/tests/api/ApiTestSteps.ts, src/tests/api/ApiUtils.ts, src/tests/api/HappyPath.test.ts, src/tests/api/e2eHappyPath.test.ts, src/tests/data/CIC_CRI_START_LOW_CONFIDENCE_SCHEMA.json, src/tests/data/happyPathKenneth.json
Add BE tests to validate CIC Low Confidence Journey
- [KIWI-1940](https://govukverify.atlassian.net/browse/KIWI-1940)
[KIWI-1940]: https://govukverify.atlassian.net/browse/KIWI-1940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1940 QA

src/tests/api/ApiTestSteps.ts, src/tests/api/HappyPath.test.ts, src/tests/api/e2eNegativePath.test.ts, src/tests/contract/data/session-items.json, src/tests/data/CIC_CRI_START_BANK_ACCOUNT_SCHEMA.json, src/tests/data/CIC_CRI_START_LOW_CONFIDENCE_SCHEMA.json, src/tests/data/CIC_CRI_START_SCHEMA.json, src/tests/data/happyPathBillyJoe.json, src/tests/data/happyPathBjörn.json, src/tests/data/happyPathKenneth.json, src/tests/data/happyPathManuel.json, src/tests/data/happyPathSlim.json, src/utils/Constants.ts
Update context values + TxMA event schema 
- [KIWI-1963](https://govukverify.atlassian.net/browse/KIWI-1963)
[KIWI-1963]: https://govukverify.atlassian.net/browse/KIWI-1963?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> QA Updates KIWI-1963

deploy/samconfig.toml, deploy/template.yaml, src/tests/infra/template.test.ts
[ KIWI-1872 ] Set AWS CloudWatch log retention to 30 days
Updated the CloudFormation template to set the retention period for all CloudWatch log groups to 30 days (1 month)
Modified the EnvironmentConfiguration mapping in the template to ensure consistent 30-day retention across all environments (dev, build, staging, integration, production)
Applied the change to all Lambda function and API Gateway log groups associated with the CIC API stack
To standardise log retention periods across all environments
To ensure compliance with data retention policies
Issue tracking
[INCIDEN-627](https://govukverify.atlassian.net/browse/INCIDEN-627?focusedCommentId=125675)
- [ CRI-BAV-FRONT ](https://github.com/govuk-one-login/ipv-cri-bav-front/pull/322)
- [ CRI-CIC-FRONT …
=> [KIWI-1872] - Set AWS CloudWatch log retention to 30 days

deploy/template.yaml
- Deployment preference
- fixing deployment when we don't have enabled lambda canary 
- [KIWI-XXXX](https://govukverify.atlassian.net/browse/KIWI-XXXX)
=> IPS-1095 updated deployment preference

.github/workflows/pull-request-sonar.yml, deploy/template.yaml
This was managed locally but is now being taken care of by FMS
Added tags to include the CloudFront distribution in a custom rule set from FMS
Added tags
to include the CloudFront distribution in a custom rule set from FMS
- [IPS-1407](https://govukverify.atlassian.net/browse/IPS-1407)
[IPS-1407]: https://govukverify.atlassian.net/browse/IPS-1407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-1407: Update to tag teh cloudfront to have a custom FMS ruleset

.github/workflows/pull-request-sonar.yml, deploy/template.yaml
Removed the WAF ACL from Dev acount as it's managd in FMS now
=> Ips 1407 migrate kiwi and lime wa fs

src/tests/api/HappyPath.test.ts, src/tests/api/e2eHappyPath.test.ts, src/tests/api/e2eNegativePath.test.ts, src/tests/contract/routes/AccessTokenRoute.ts, src/tests/contract/routes/UserInfoRoute.ts, src/tests/unit/AbortHandler.test.ts, src/tests/unit/AccessTokenHandler.test.ts, src/tests/unit/AuthorizationCodeHandler.test.ts, src/tests/unit/ClaimedIdentityHandler.test.ts, src/tests/unit/JwksHandler.test.ts, src/tests/unit/SessionConfigHandler.test.ts, src/tests/unit/SessionHandler.test.ts, src/tests/unit/UserInfoHandler.test.ts, src/tests/unit/services/AccessTokenRequestProcessor.test.ts, src/tests/unit/services/AuthorizationRequestProcessor.test.ts, src/tests/unit/services/CicService.test.ts, src/tests/unit/services/ClaimedIdRequestProcessor.test.ts, src/tests/unit/services/SessionConfigRequestProcessor.test.ts, src/tests/unit/services/SessionRequestProcessor.test.ts, src/tests/unit/services/UserInfoRequestProcessor.test.ts, src/tests/unit/utils/EnvironmentVariables.test.ts
Happy Path: 
E2E Happy Path: 
Update Test Descriptions for better readability
Retro Action
=> Update Test Descriptions for better readability

src/tests/api/ApiTestSteps.ts, src/tests/api/HappyPath.test.ts, src/tests/api/e2eHappyPath.test.ts, src/tests/api/e2eNegativePath.test.ts
/token endpoint Core Consumption QA
- [KIWI-2271](https://govukverify.atlassian.net/browse/KIWI-2271)
[KIWI-2271]: https://govukverify.atlassian.net/browse/KIWI-2271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-2271: /token Core Consumption QA

run-tests.sh
Update env variable to ensure correct stub URL is hit
Causing failed pipeline runs
- [KIWI-2271](https://govukverify.atlassian.net/browse/KIWI-2271)
[KIWI-2271]: https://govukverify.atlassian.net/browse/KIWI-2271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-2271: Update run-tests.sh env variables

deploy/template.yaml
- [KIWI-2437](https://govukverify.atlassian.net/browse/KIWI-2437)
[KIWI-2437]: https://govukverify.atlassian.net/browse/KIWI-2437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-2437 - Enable key rotation in integration environment

deploy/template.yaml
Reversion of KIWI-2476 changes
=> [KIWI-2476] - Reversion
