govuk-one-login/ipv-cri-cic-api

- lambda-functions/template.yaml
Added tag to HelloWorld to skip CKV_AWS_116 (DLQ), also added this to be skipped in the checkov hook in aws console.
> F2F-76t4: Adjusted HelloWorld to skip CKV_AWS_116

- .github/workflows/post-merge-package-to-build.yml
- .github/workflows/post-merge-package-to-dev.yml
- .github/workflows/pull-request.yml
Added new github secrets to both build and dev workflows as the BE is being renamed in line with our new pipelines (and away from "V1" convention)
BUILD_CRI_CIC_GH_ACTIONS_ROLE_ARN
BUILD_CRI_CIC_ARTIFACT_SOURCE_BUCKET_NAME
BUILD_CRI_CIC_SIGNING_PROFILE_NAME
DEV_CRI_CIC_GH_ACTIONS_ROLE_ARN
DEV_CRI_CIC_ARTIFACT_SOURCE_BUCKET_NAME
DEV_CRI_CIC_SIGNING_PROFILE_NAME
The values of these secrets were also updated from the outputs of the new pipeline.
- [F2F-358](https://govukverify.atlassian.net/browse/F2F-358)
[F2F-358]: https://govukverify.atlassian.net/browse/F2F-358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> F2F-358:Added new BE name to workflow file secrets

- infra-l2-dynamo/template.yaml
Removing the access-token index from the sessionTable
We dont need this index
- [F2F-306](https://govukverify.atlassian.net/browse/F2F-306)
- [F2F-307](https://govukverify.atlassian.net/browse/F2F-307)
[F2F-306]: https://govukverify.atlassian.net/browse/F2F-306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[F2F-307]: https://govukverify.atlassian.net/browse/F2F-307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [F2F-306] dynamo db updates

- deploy/cic-spec.yaml
- src/tests/unit/models/CicSession.test.ts
Enum list for documentSelection types.
Updated it with the currently used enum in the front-end app. Need confirmation from IPV Core team on the same.
- [F2F-403](https://govukverify.atlassian.net/browse/F2F-403)
[F2F-403]: https://govukverify.atlassian.net/browse/F2F-403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [F2F-403]-Update OpenAPI with relevant enums for the different document types

- .github/workflows/pull-request-Dynamo.yml
- .github/workflows/pull-request-KMS.yml
- .github/workflows/pull-request-WAF.yml
- .github/workflows/pull-request-ipv-stub.yml
- .github/workflows/pull-request.yml
Removed reference to environment: di-ipv-cri-dev in order to allow us to delete common infrastructure from out AWS accounts and not have them redeployed. 
So that we can remove common infrastructure.
- [F2F-373](https://govukverify.atlassian.net/browse/F2F-373)
[F2F-373]: https://govukverify.atlassian.net/browse/F2F-373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> F2F-373: Removed common cri environment

- cic-ipv-stub/samconfig.toml
- cic-ipv-stub/template.yaml
Change backend stack ref for cic-ipv-stub
Referring to backend-main stack in build account which doesn't exist
> Change backend stack ref for cic-ipv-stub

- .github/workflows/pull-request-sonar.yml
- infra-l2-dynamo/jest.config.ts
- infra-l2-kms/jest.config.ts
- sonar-project.properties
- src/package.json
Implement sonar scan properties and workflow to run sonar scan on the di-ipv-cri-cic-api.
This includes the scan files, exclusions and code coverage.
Also modified the jest config to allow coverage
- [F2F-100](https://govukverify.atlassian.net/browse/F2F-100)
[F2F-100]: https://govukverify.atlassian.net/browse/F2F-100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> F2F-100: Add Sonar scan to ipv-cri-cic-api

- README.md
- deploy/template.yaml
Externalised log level in SAM/CFN template as a parameter with INFO as the default.
Ease of deploying stacks in DEV with DEBUG log level setting
- [F2F-586](https://govukverify.atlassian.net/browse/F2F-586)
[F2F-586]: https://govukverify.atlassian.net/browse/F2F-586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> F2F-586 Externalised powertools log level in template

- cic-ipv-stub/template.yaml
Added dns suffix environment variables to the stub template
Deployment was failing due to missing env var.
- [F2F-593](https://govukverify.atlassian.net/browse/F2F-593)
[F2F-593]: https://govukverify.atlassian.net/browse/F2F-593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> F2F-593:Added environmentvariables to stub template

- cic-ipv-stub/src/handlers/startCicCheck.ts
- src/tests/unit/services/SessionRequestProcessor.test.ts
- src/tests/unit/services/UserInfoRequestProcessorNoConfiguration.test.ts
Adding flag addSharedClaims to the IPV Stub in CIC to enable testing of scenarios where IPV do not provide us with shared_claims information 
https://govukverify.atlassian.net/browse/F2F-657
```
{
"target": "https://api-cic-cri-api.review-c.dev.account.gov.uk/",
"addSharedClaims": false
}
```
> [F2F-657] - Add shared_claims Flag to IPV stub

- deploy/template.yaml
- src/tests/infra/template.test.ts
DataTraceEnabled is now set based on environments - it is false in environments which contain in PII
avoid logging PII
- [F2F-720](https://govukverify.atlassian.net/browse/F2F-720)
[F2F-720]: https://govukverify.atlassian.net/browse/F2F-720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> F2F-720 DataTraceEnabled switched based on env, + tests

- cic-ipv-stub/template.yaml
The dev and build IPVSTUB URLs have been updated to hopefully work
It wasn't working, an old URL was being called
- [F2F-766](https://govukverify.atlassian.net/browse/F2F-766)
[F2F-766]: https://govukverify.atlassian.net/browse/F2F-766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [F2F-766] - Updating IPV stub URLs

- deploy/template.yaml
- src/tests/infra/template.test.ts
Template Output CICBackendURL now uses value from CICApiCustomDomainName 
The current value for CICBackendURL has incorrect value in environments other than development as it used the format api-{stack name}-{domainname}. cic back end domain name has only api without the stack name.
- [F2F-820](https://govukverify.atlassian.net/browse/F2F-820)
CICBackendURL has been changed to use value from CICApiCustomDomainName in the template.
[F2F-820]: https://govukverify.atlassian.net/browse/F2F-820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Changed CICBackendURL output to use correct value for all env

- src/UserInfoHandler.ts
- src/services/CicService.ts
- src/services/UserInfoRequestProcessor.ts
- src/tests/unit/services/UserInfoRequestProcessor.test.ts
We are no longer logging the session ID as that is the user ID and is considered PII
We cannot log PII
Before
After
- [F2F-850](https://govukverify.atlassian.net/browse/F2F-850)
- This is being merged into F2F-615 as it cannot be merged while the service is still logging PII
[F2F-850]: https://govukverify.atlassian.net/browse/F2F-850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [F2F-850] Ensures user id is not logged

- src/SessionHandler.ts
- src/services/SessionRequestProcessor.ts
Added log that could be helpful for debugging
While checking for logs that might contain PII, I noticed that a log confirming the lambda has been successfully triggered as we have in other services was not present here
- [F2F-846](https://govukverify.atlassian.net/browse/F2F-846)
[F2F-846]: https://govukverify.atlassian.net/browse/F2F-846?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [F2F-846] Adds log to session endpoint

- run-tests.sh
run-tests.sh script was updated to use src dir path from root.
Caused the test to fail once the platform codepipeline changes were applied as the run-tests.sh script incorrectly assumed to be running in root dir.
- [F2F-895](https://govukverify.atlassian.net/browse/F2F-895)
[F2F-895]: https://govukverify.atlassian.net/browse/F2F-895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fixed the test to provide absolute path for src directory

- .github/CODEOWNERS
Added `@alphagov/di-ipv-kiwi-api-codeowners` to the list of code owners for the `/tests` repo so that we can approve test changes too
Currently the QA team are the _only_ approvers for test changes which is blocking us when we make changes too unit tests etc
> Adds API codeowners to the tests repo aswell

- deploy/template.yaml
Added a new condition IsNotProdLikeEnvironment to skip export of CICIPVStubExecuteURL as it is not needed in staging, integration and prod.
The codepipeline deployment was failing in staging for cic api.
- [F2F-905](https://govukverify.atlassian.net/browse/F2F-905)
[F2F-905]: https://govukverify.atlassian.net/browse/F2F-905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Adding condition to skip output CICIPVStubExecuteURL in prod like env

- src/services/CicService.ts
Logs table name instead of updated command
The update command contains `sub`/`user id`
Before
After
- [F2F-843](https://govukverify.atlassian.net/browse/F2F-843)
[F2F-843]: https://govukverify.atlassian.net/browse/F2F-843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [F2F-843] Stops loggings update command as it contains PII

- cic-ipv-stub/src/handlers/startCicCheck.ts
- cic-ipv-stub/src/tests/startCicCheck.test.ts
- cic-ipv-stub/template.yaml
Fixing change done [here](https://github.com/alphagov/di-ipv-cri-cic-api/pull/219/files) to correctly set the BE stack url so IPVStub is able to fetch the WellKnown endpoint
> [CIC-962] Update main stack url for IPVStub

- README.md
- deploy/template.yaml
Set reserved concurrencies for all lambdas which are deployed in all non-DEV environments. These are required in BUILD since this is the environment used in performance testing. A parameter has been added to allow them to be set when manually deploying in DEV should this be needed, but this must not be default.
Per requirements on ticket
- [F2F-779](https://govukverify.atlassian.net/browse/F2F-779)
[F2F-779]: https://govukverify.atlassian.net/browse/F2F-779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> F2F-779: Set reserved concurrencies for Lambdas in non-DEV environments

- test-harness/template.yaml
Set `AlwaysDeploy: true` for test harness api gateway definition
To redeploy even if changes aren't detected (api gateway is currently using the wrong role)
> Forcing test harness apigw redeploy

- deploy/template.yaml
TESTHARNESS definition in build main template
was previously incorrect causing the test-container in build to fail and the pipeline to be blocked
- [F2F-1135](https://govukverify.atlassian.net/browse/F2F-1135)
[F2F-1135]: https://govukverify.atlassian.net/browse/F2F-1135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> F2F-1135 Update TESTHARNESS in BUILD main template

- infra-l2-dynamo/template.yaml
- test-harness/test-harness-spec.yaml
Removing the unused authorizationCode-index index and its references as a new index authCode-index was introduced as part of F2F-1080
authCode-index was added and deployed in prod which is working as expected and the old index is ununsed and needs to be removed.
- [F2F-1098](https://govukverify.atlassian.net/browse/F2F-1098)
[F2F-1098]: https://govukverify.atlassian.net/browse/F2F-1098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [F2F[1098] Removing the unused authorizationCode-index index and its references.

- infra-l2-dynamo/template.yaml
- src/services/AccessTokenRequestProcessor.ts
- src/utils/Constants.ts
- test-harness/test-harness-spec.yaml
Addes expiryDate to `GlobalSecondaryIndexes` so that it is returned when session table is queried using `authorizationCode-index`
Because the returned record did not include `expiryDate` and therefore the expired check wasn't working
No regression on sign in ID
- [F2F-672](https://govukverify.atlassian.net/browse/F2F-672)
[F2F-672]: https://govukverify.atlassian.net/browse/F2F-672?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [F2F-672] Creates new GlobalSecondaryIndexes for expired session check

- infra-l2-dynamo/template.yaml
Removing Unused authCode-index
Tech debt
- [KIWI-1137](https://govukverify.atlassian.net/browse/KIWI-1137)
Evidences:
Before indexes:
After index list:
[KIWI-1137]: https://govukverify.atlassian.net/browse/KIWI-1137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-1137] Remove Unused authCode-index

- Dockerfile
Replaces deprecated script in Dockerfile
To save time in our local runs
- [F2F-1299](https://govukverify.atlassian.net/browse/F2F-1299)
No issues when running `run-tests-locally`
> [KIWI-1299] Replaces deprecated script in Dockerfile

- src/services/AuthorizationRequestProcessor.ts
- src/services/ClaimedIdRequestProcessor.ts
- src/tests/unit/services/AuthorizationRequestProcessor.test.ts
- src/tests/unit/services/ClaimedIdRequestProcessor.test.ts
Updates the state checks in Authorization Lambda to return a 200 if the session state is CIC_DATA_RECEIVED, CIC_AUTH_CODE_ISSUED or CIC_ACCESS_TOKEN_ISSUED
In Authorization Lambda for a duplicate request rather than generate a new AuthCode we query the DB and return the authCode that's already in the DB 
As part of https://github.com/govuk-one-login/ipv-cri-cic-api/pull/334 the change was made to claimedIdentity to return 200 to cover scenario when user double clicks or when they go back on the browser and forward again, since then the error was still seen and reason for it was due to the change also needing to be made in the Auth lambda 
**Before**
**After**
> [KIWI-933] - Update session state checks in Authorization Lambda

- .github/CODEOWNERS
- .github/pull_request_template.md
- src/package.json
- Add the CODEOWNERS for new govuk-one-login github CIC API
- Modified the urls pointing to alphagov github repository
- [F2F-1320](https://govukverify.atlassian.net/browse/F2F-1320)
> KIWI-1320: Github migration - Post-migration cleanup for CIC API

- deploy/template.yaml
- Integrate Lambda functions to ingest metrics in dynatrace 
- Add dyntrace SSM parameters and inject lambda logs to dynatrace
- This will allow dynatrace to get lambda metric from the CIC service
- [KIWI-1502](https://govukverify.atlassian.net/browse/KIWI-1502)
[KIWI-1502]: https://govukverify.atlassian.net/browse/KIWI-1502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-1502:Enable Lambda metrics in Dynatrace

- .github/workflows/pull-request-sonar.yml
Stops running sonar checks for dependabot PRs
So that dependabot PR checks can succeed
- [KIWI-1530](https://govukverify.atlassian.net/browse/KIWI-1530)
[KIWI-1530]: https://govukverify.atlassian.net/browse/KIWI-1530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-1530: Don't run sonar checks for dependabot PRs

- deploy/template.yaml
- Existing 4xx and 5xx alarms does not create invocations and errors.
- ApiName is configured wrong due to which invocations does not happen
- Add Accesslogsettings to send more metrics
- Modified access log settings on the API Gateway.
- Modified API Name confgiuration.
- ApiName configured incorrect causes a issue with getting invocations
- Accesslogsettings require additinal parameters to alerts
- [KIWI-1497](https://govukverify.atlassian.net/browse/KIWI-1497)
[KIWI-1457]: https://govukverify.atlassian.net/browse/KIWI-1457?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KIWI-1497]: https://govukverify.atlassian.net/browse/KIWI-1497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-1497: Fix API name on 5xx and 4xx Alarms

- src/tests/api/e2eHappyPath.test.ts
- src/tests/data/CIC_CRI_START_BANK_ACCOUNT_SCHEMA.json
- src/tests/utils/ApiTestSteps.ts
Update logic to validate CIC_CRI_START event with extension block
Validation of CIC_CRI_START when triggered in a No photo ID/ BAV journey
> Update logic to validate CIC_CRI_START event with extension block

- src/tests/api/ApiTestSteps.ts
- src/tests/api/ApiUtils.ts
- src/tests/api/HappyPath.test.ts
- src/tests/data/CIC_CRI_SESSION_ABORTED_SCHEMA.json
- src/utils/TxmaEvent.ts
Added two tests in `HappyPathTest` 
To validate the abort endpoints from the Claimed Identity Collector
- [KIWI-1658](https://govukverify.atlassian.net/browse/KIWI-1658)
[KIWI-1658]: https://govukverify.atlassian.net/browse/KIWI-1658?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-1658-abort endpoint-QA

- deploy/template.yaml
Alarms are created on dev for every custom stack created on the dev account. 
In order to optimise the stack, alarm is set to off by default 
Change the flag to deploy on dev set to false.
Added the condition on metric filter and alarms
Modified the concurrency alarms flag.
Too many alarms created when a new custom is created.
- [KIWI-1717](https://govukverify.atlassian.net/browse/KIWI-1717)
- [IPS-678](https://govukverify.atlassian.net/browse/IPS-678)
[KIWI-1717]: https://govukverify.atlassian.net/browse/KIWI-1717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-678]: https://govukverify.atlassian.net/browse/IPS-678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-1717: Set Alarms to Off by Default in Dev

- src/tests/data/CIC_CRI_SESSION_ABORTED_SCHEMA.json
- src/tests/data/CIC_CRI_START_BANK_ACCOUNT_SCHEMA.json
- src/tests/data/CIC_CRI_START_SCHEMA.json
QA changes to validate the following AC
Include the encoded header in the restricted.device_information.encoded field of TxMA events emitted by the corresponding lambdas:
- CIC_CRI_START
- CIC_CRI_SESSION_ABORTED
- [KIWI-1780](https://govukverify.atlassian.net/browse/KIWI-1780)
[KIWI-1780]: https://govukverify.atlassian.net/browse/KIWI-1780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update JSON Schema for TxMA events impacted by KIWI-1780

- deploy/cic-spec.yaml
- src/AbortHandler.ts
- src/services/AbortRequestProcessor.ts
- src/services/CicService.ts
- src/services/SessionRequestProcessor.ts
- src/tests/api/ApiTestSteps.ts
- src/tests/data/CIC_CRI_SESSION_ABORTED_SCHEMA.json
- src/tests/data/CIC_CRI_START_BANK_ACCOUNT_SCHEMA.json
- src/tests/data/CIC_CRI_START_SCHEMA.json
- src/tests/unit/AbortHandler.test.ts
- src/tests/unit/data/abort-events.ts
- src/tests/unit/data/session-events.ts
- src/tests/unit/services/SessionRequestProcessor.test.ts
- src/utils/Constants.ts
- src/utils/IVeriCredential.ts
- src/utils/TxmaEvent.ts
- src/utils/Validations.ts
- Add AuditHeader to /session API spec
- Add AuditHeader to /abort API spec
- Include the encoded header in the restricted.device_information.encoded field of TxMA events emitted by the corresponding lambdas:
- CIC_CRI_START
- CIC_CRI_SESSION_ABORTED
- Update logic first attempt getting the sourceIp from the X-Forwarded-For header, and only revert to checking the event.requestContext.identity?.sourceIp if not present
Required for CloudFront initiative
- [KIWI-1780](https://govukverify.atlassian.net/browse/KIWI-1780)
API tests passing
/session endpoint with headers:
/abort endpoint with headers
[KIWI-1780]: https://govukverify.atlassian.net/browse/KIWI-1780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-1780] - CIC | CloudFront initiative | BE | Add the CF Header for User - Machine Calls

- src/services/SessionRequestProcessor.ts
- src/tests/api/ApiTestSteps.ts
- src/tests/api/ApiUtils.ts
- src/tests/api/HappyPath.test.ts
- src/tests/api/e2eHappyPath.test.ts
- src/tests/data/CIC_CRI_START_LOW_CONFIDENCE_SCHEMA.json
- src/tests/data/happyPathKenneth.json
- src/utils/Constants.ts
- src/utils/ValidationHelper.ts
Added functionality to accept "hmrc_check" context property in call from IPV, save this as "LOW_CONFIDENCE" in the journey property in Dynamo DB session table and return in session-config call
To route users on the front end to the low confidence journey
- [KIWI-1940](https://govukverify.atlassian.net/browse/KIWI-1940)
[KIWI-1940]: https://govukverify.atlassian.net/browse/KIWI-1940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-1940] - CIC | BE | Handle new Core flag for Low Confidence Journeys

- src/services/SessionRequestProcessor.ts
- src/tests/api/ApiTestSteps.ts
- src/tests/api/HappyPath.test.ts
- src/tests/api/e2eNegativePath.test.ts
- src/tests/contract/data/session-items.json
- src/tests/data/CIC_CRI_START_BANK_ACCOUNT_SCHEMA.json
- src/tests/data/CIC_CRI_START_LOW_CONFIDENCE_SCHEMA.json
- src/tests/data/CIC_CRI_START_SCHEMA.json
- src/tests/data/happyPathBillyJoe.json
- src/tests/data/happyPathBjörn.json
- src/tests/data/happyPathKenneth.json
- src/tests/data/happyPathManuel.json
- src/tests/data/happyPathSlim.json
- src/tests/unit/services/SessionRequestProcessor.test.ts
- src/utils/Constants.ts
- src/utils/TxmaEvent.ts
- src/utils/ValidationHelper.ts
Updated `/session` logic to directly store the value for the journey context provided in the initial request from core into the `session-table`. Additionally, fixed the structure of the TxMA event emitted for `CIC_CRI_START` and included the 'f2f' context value for default journeys (i.e. no value for journey context in initial request)
- [KIWI-1963](https://govukverify.atlassian.net/browse/KIWI-1963)
With `hmrc_check` flag
Without context flag in initial request - defaults to `f2f`
[KIWI-1963]: https://govukverify.atlassian.net/browse/KIWI-1963?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update /session to include new context flags for journey type

- .github/workflows/pull-request-sonar.yml
- .github/workflows/run-unit-tests.yml
- .github/workflows/scan-repo.yml
- sonar-project.properties
- src/tsconfig.json
Added github actions to run sonar on pushes to main
So that we can effectively monitor Kiwi services
> KIWI-1958: Added actions to perform sonar scans on main

- deploy/cic-spec.yaml
- Added `maxlength` validation to the Name fields in the CIC, restricting the length to 40 characters to prevent excessively large payloads. The maximum possible payload is now capped at 98 characters.
- Implemented special character validation for the Name fields in the CIC API spec, ensuring consistent validation across both frontend and backend.
- Matched the regular expression pattern for name validation from the frontend to the backend, aligning validation rules.
- Added a `minLength` validation of 2 characters for properties of type `string`, ensuring all Name fields comply with frontend validation rules.
- Added `maxLength` validation of `18` to the DOB.
- [BAV-API-1987](https://github.com/govuk-one-login/ipv-cri-bav-api/pull/253) …
> [KIWI-1987] Add max length validation to name fields within the API Spec

- .github/workflows/pull-request-sonar.yml
- .github/workflows/scan-repo.yml
Bumped the GH Action to use the new SonarCloud GH Action
version pin
Upstream action deprecated
https://govukverify.atlassian.net/browse/IPS-1428
> Updating SonarCube GH Action to avoid deprecation

- .secrets.baseline
- src/tests/unit/utils/JwtUtils.test.ts
Adds unit tests for JwtUtils module
To increase code coverage and dependability of service
- [KIWI-2115](https://govukverify.atlassian.net/browse/KIWI-2115)
[KIWI-2115]: https://govukverify.atlassian.net/browse/KIWI-2115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-2115] - Write unit tests for all methods of the JwtUtils class

- .secrets.baseline
- cic-ipv-stub/src/handlers/jsonWebKeys.ts
- cic-ipv-stub/src/tests/jsonWebKeys.test.ts
- cic-ipv-stub/template.yaml
Added additional JWK to IPV stub 'well-known' endpoint  response - this is a different, valid key with a different `kid` to the one currently used
To remain aligned with the IPV core service
- [KIWI-2219](https://govukverify.atlassian.net/browse/KIWI-2219)
[KIWI-2219]: https://govukverify.atlassian.net/browse/KIWI-2219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-2219 - OAuth | Add second key to IPV Core Stub

- src/tests/api/ApiTestSteps.ts
- src/tests/api/e2eNegativePath.test.ts
Add Negative Testing Scenario for: 
**AC3**: Request NOT verified as originating from Core
**GIVEN** the initial request was made by Core
**WHEN** the signature is NOT verified using Core’s signing key
**THEN** a 401 Unauthorised response is returned
- [KIWI-2192](https://govukverify.atlassian.net/browse/KIWI-2192)
[KIWI-2192]: https://govukverify.atlassian.net/browse/KIWI-2192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Kiwi 2192 QA Updates

- src/services/SessionRequestProcessor.ts
- src/tests/api/ApiTestSteps.ts
- src/tests/api/e2eNegativePath.test.ts
- src/utils/Constants.ts
BackEnd changes allow us to test for missingKid scenario by adding a new key to the start Stub payload (missingKid = true) 
Tests added to validate we're able to return a 401 status code and Unauthorised error message when hitting the session endpoint with a JWT with a missingKid.
- [KIWI-XXXX](https://govukverify.atlassian.net/browse/KIWI-XXXX)
> Key Rotation: Update logic to test for missingKid

- infra-l2-kms/template.yaml
Reverts govuk-one-login/ipv-cri-cic-api#645
Kiwi are migrating to use https://github.com/govuk-one-login/ipv-cri-common-infrastructure/blob/main/core/template.yaml (same as Lime and Orange), so do not need a new bucket in the L2 stack
> Revert "IPS-1516: Create bucket for key rotation"

- deploy/template.yaml
S3 bucket policy fix
- [KIWI-2306](https://govukverify.atlassian.net/browse/KIWI-2306)
[KIWI-2306]: https://govukverify.atlassian.net/browse/KIWI-2306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-2306] - CIC | OAuth | Move public encryption keys to new S3

- deploy/cic-spec.yaml
- deploy/template.yaml
Added a new temporary APIGW endpoint that integrates with the new `published-keys` bucket.
The sole purpose of this endpoint is to confirm the contents of the new `published-keys` bucket, which is published to alongside the existing `JsonWebKeysBucket`. This cannot be done via the AWS console due to restrictions applied on the new bucket. Once the contents are confirmed, this endpoint should be removed in a followup PR that integrates the new bucket with the existing `well-known `e/p.
- [KIWI-2370](https://govukverify.atlassian.net/browse/KIWI-2370)
[KIWI-2370]: https://govukverify.atlassian.net/browse/KIWI-2370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-2370 - Verify new S3 bucket and connect to existing JWKS endpoint

- deploy/template.yaml
Disabled JsonWebKeysFunction scheduled invocation
To prevent the lambda publishing JWKs to the S3 bucket used by the ./well-known endpoint, as this action overwrites keys published by the key rotation stack to the same bucket
> Disable JsonWebKeysFunction scheduled invocation

- deploy/template.yaml
Switch Dynatrace Layers away from SecretsManager by hardcoding lambda to Dynatrace layer ARN
- [KIWI-2443](https://govukverify.atlassian.net/browse/KIWI-2443)
[KIWI-2443]: https://govukverify.atlassian.net/browse/KIWI-2443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-2443 - Switch Dynatrace Layers away from SecretsManager
